version: '2'

services:
    anyconnectvpn:
      build: ./scripts
      restart: always
      network_mode: host
      privileged: true
      environment:
        - ANYCONNECT_SERVER=${ANYCONNECT_SERVER}
        - ANYCONNECT_USER=${ANYCONNECT_USER}
        - ANYCONNECT_PASSWORD=${ANYCONNECT_PASSWORD}
        - ServerCert=${ServerCert}
        - RDPGateway=${RDPGateway}
        - RDPPort=${RDPPort}
        - LasernetPort=${LasernetPort}